// Helper file to make coverage work for all dart files
// **************************************************************************
// Because of this: https://github.com/flutter/flutter/issues/27997#issue-410722816
// DO NOT EDIT THIS FILE USE: sh scripts/import_files_coverage.sh lcov_test
// **************************************************************************

// ignore_for_file: unused_import
import 'package:lcov_test/core/errors/exceptions.dart';
import 'package:lcov_test/features/home/data/datasources/home_remote_data_source.dart';
import 'package:lcov_test/features/home/data/datasources/home_client.dart';
import 'package:lcov_test/features/home/domain/entities/article.dart';
import 'package:lcov_test/features/home/presentation/pages/home_page.dart';
import 'package:lcov_test/main.dart';

void main(){}